apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: ZGV2X3Bvc3RncmVz #dev_postgres
  password: ZGFzcXVlZQ== #dasquee

#echo -n 'dev_postgres' | openssl base64
